#!/usr/bin/env bash
# Regenerate the iOS app-icon + splash SOURCES for @capacitor/assets.
# Run from the repo root: bash scripts/gen-ios-assets.sh
#
# These are NOT web assets. The native iOS app icon + launch screen live in the Xcode
# asset catalog (ios/App/App/Assets.xcassets — ios/ is gitignored / generated by
# `npx cap add ios`). @capacitor/assets reads the files below and writes that catalog.
#
# Sources (committed):
#   scripts/assets/app-icon.svg      -> assets/icon.png        (1024, opaque, square, NO alpha)
#   scripts/assets/splash-light.svg  -> assets/splash.png      (2732, #FBF6EC light)
#   scripts/assets/splash-dark.svg   -> assets/splash-dark.png (2732, #1C1C1E dark)
#
# App Store icon rules enforced here: 1024x1024, opaque (alpha stripped — App Store
# rejects an alpha channel), square corners (iOS applies its own superellipse mask).
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p assets

echo "→ assets/icon.png (1024, opaque)"
rsvg-convert -w 1024 -h 1024 scripts/assets/app-icon.svg -o assets/icon.png
magick assets/icon.png -background '#1B2A4A' -alpha remove -alpha off assets/icon.png

echo "→ assets/splash.png (2732, light)"
rsvg-convert -w 2732 -h 2732 scripts/assets/splash-light.svg -o assets/splash.png
echo "→ assets/splash-dark.png (2732, dark)"
rsvg-convert -w 2732 -h 2732 scripts/assets/splash-dark.svg -o assets/splash-dark.png

echo "✓ iOS asset sources regenerated"
echo
echo "Next (after the iOS shell exists — Phase 1 / 01-01 runs 'npx cap add ios'):"
echo "  npx @capacitor/assets generate --ios"
echo "  npx cap sync ios"
